apiVersion: apps/v1
kind: Deployment
metadata:
  name: TestAuto
  labels:
    app: TestAuto
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TestAuto
  template:
    metadata:
      labels:
        app: TestAuto
    spec:
      containers:
        - name: TestAuto
          image: dcakstestregistry.azurecr.io/image-workflow-1689745545439:latest
          ports:
            - containerPort: 8000