apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy
  labels:
    app: autodeploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy
  template:
    metadata:
      labels:
        app: autodeploy
    spec:
      containers:
        - name: autodeploy
          image: dcakstestregistry.azurecr.io/image-workflow-1689769758243:latest
          ports:
            - containerPort: 80