apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy
  labels:
    app: autodeploy
  namespace: namespace-workflow-1689683569945
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy
  template:
    metadata:
      labels:
        app: autodeploy
    spec:
      containers:
        - name: autodeploy
          image: DCAKSTESTregistry.azurecr.io/image-workflow-1689683569945:latest
          ports:
            - containerPort: 8000