apiVersion: v1
kind: Service
metadata:
  name: autodeploy
  namespace: namespace-workflow-1689743432020
spec:
  type: LoadBalancer
  selector:
    app: autodeploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80