apiVersion: v1
kind: Service
metadata:
  name: TestAuto
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: TestAuto
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000